Больше деталей
htmlacademy-javascript/1932495-kekstagram-26 pull request #3
Opened 2022-06-17 14:12 UTC by prokhanova-k

2022-06-17 18:05 UTC, AlexMasterov requested changes

2022-06-17 18:05 UTC, AlexMasterov commented on js/main.js
> +/* eslint-disable indent */
Предупреждаю, что на защите линтер игнорирует подобные директивы.

Лучше для правила `indent` используй _автоисправление_:

```
npx eslint src/ --fix
npm run lint --fix
```
> Еще лучше не писать код, который нарушает это правило 😃

2022-06-17 18:05 UTC, AlexMasterov commented on js/main.js
> +const DESCRIPTION = [
[`Б 5`](https://up.htmlacademy.ru/javascript/26/criteries#b5)
> Массивы названы существительными во множественном числе

2022-06-17 18:05 UTC, AlexMasterov commented on js/main.js
> +const MESSAGE = [
[`Б 5`](https://up.htmlacademy.ru/javascript/26/criteries#b5)
> Массивы названы существительными во множественном числе

2022-06-17 18:05 UTC, AlexMasterov commented on js/main.js
> +const getRandomPositiveInteger = (a, b) => {
```diff
- const getRandomPositiveInteger = (a, b) => {
+ const getRandomPositiveInteger = (min, max) => {
```

2022-06-17 18:05 UTC, AlexMasterov commented on js/main.js
> +const getRandomArrayElement = (elements) => elements[getRandomPositiveInteger(0, elements.length - 1)];
```diff
- const getRandomArrayElement = (elements) => elements[getRandomPositiveInteger(0, elements.length - 1)];
+ const getRandomArrayItem = (items) => items[getRandomPositiveInteger(0, items.length - 1)];
```

2022-06-17 18:05 UTC, AlexMasterov commented on js/main.js
> +const shuffleArray = (array) => {
const shuffleArray = (`array`) => {

[`Б 5`](https://up.htmlacademy.ru/javascript/26/criteries#b5)
> Массивы названы существительными во множественном числе

> `array` -> `items`

2022-06-17 18:05 UTC, AlexMasterov commented on js/main.js
> +// const { name } = require("browser-sync");
🤔

2022-06-17 18:05 UTC, AlexMasterov commented on js/main.js
> +function getRandomInteger (min,max) {
См. https://github.com/htmlacademy-javascript/1932495-kekstagram-26/pull/2#discussion_r893258105.

`function` getRandomInteger (min,max) {

[`Д 5`](https://up.htmlacademy.ru/javascript/26/criteries#d5)
> Все функции объявлены единообразно

> При объявлении функций используются _стрелочные_ функции

2022-06-17 18:05 UTC, AlexMasterov commented on js/main.js
> +const createPhotoComments = () => ({
const createPhotoComment`s` = () => (`{`

Функция создает _один_ объект с данными комментария, но при этом называется во множ. числе.

[`Б 6`](https://up.htmlacademy.ru/javascript/26/criteries#b6)
> Название функции или метода должно быть глаголом и **соответствовать действию**, которое выполняет функция или метод

2022-06-17 18:05 UTC, AlexMasterov commented on js/main.js
> +      message: shuffleArray(MESSAGE).slice(0, getRandomPositiveInteger(1, 2)),
<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/174351944-695c94c4-69fc-420a-8df8-d66b65d78802.png)

</details>

<details>
<summary>Ожидание</summary>

![image](https://user-images.githubusercontent.com/700213/174351858-0e07598f-95b9-4ed8-8a01-01478ba29349.png)
![image](https://user-images.githubusercontent.com/700213/174352306-127b8e0d-b9c7-4e57-965b-b2d669135043.png)

</details>

Значением свойства `message` должна быть одна _строка_, а не _массив_ строк.

См. задание:
> вам необходимо взять одно или два случайных предложения

Достаточно случайным образом брать одно предложение. В случае получения двух, их по итогу следует соединить в одну строку.

Нужно исправить.

2022-06-17 18:05 UTC, AlexMasterov commented on js/main.js
> +createPhotos();
Желательно доработать функцию, чтобы при её использовании через аргумент (внешним образом) можно было задать количество объектов с данными фото:

```js
createPhotos(25);
```
Еще лучше:

```js
const somePhotos = createPhotos(25, {
  comments: { min: 0, max: 10 },
});
```

> Далее это может быть полезным для тестирования некоторых пунктов ТЗ

2022-06-18 13:00 UTC, prokhanova-k commented on js/main.js
> +// const { name } = require("browser-sync");
> 🤔

Я не очень понимаю, как появилась эта строка "// const { name } = require("browser-sync");". Руками я её не прописывала, просто заметила в какой-то момент.

2022-06-19 21:21 UTC, AlexMasterov approved these changes
👍🏻

2022-06-19 21:21 UTC, AlexMasterov commented on js/main.js
> +const somePhotos = createPhotos(25);
const somePhotos = createPhotos(`25`);

Чтобы это работало, нужно было доработать функцию 😃

<details>
<summary>main.js</summary>

https://github.com/htmlacademy-javascript/1932495-kekstagram-26/blob/50ee19718f50c3248b23a9c45938ce8cf3586829/js/main.js#L79
https://github.com/htmlacademy-javascript/1932495-kekstagram-26/blob/50ee19718f50c3248b23a9c45938ce8cf3586829/js/main.js#L81
</details>

```diff
- const createPhotos = () => {
+ const createPhotos = (count) => {
```
```diff
- for (let i = 1; i <= 25; i++) {
+ for (let i = 1; i <= count; i++) {
```

2022-06-19 21:21 UTC, merged