Отрисуй меня полностью. Часть 1.
htmlacademy-javascript/1932495-kekstagram-26 pull request #5
Opened 2022-06-27 17:47 UTC by prokhanova-k

2022-06-27 18:34 UTC, AlexMasterov requested changes

2022-06-27 18:34 UTC, AlexMasterov commented on js/random.js
> +const checkTextLength = (text, maxLength) => text.length <= maxLength;
Это функция-предикат, которая проверяет максимальную длину строки. Что она делает в модуле с названием `random.js`, где собраны функции генерации случайных значений? 🤔

Нужно вернуть в `util.js`.

2022-06-27 18:34 UTC, AlexMasterov commented on js/create-thumbnails.js
> +  const pictureElement = templatePicture.cloneNode(true);
const picture`Element` = templatePicture.cloneNode(true);

<details>
<summary>create-thumbnails.js</summary>

https://github.com/htmlacademy-javascript/1932495-kekstagram-26/blob/8e9d2332cb07b954fb0ef13e1d64a9850e8cbe33/js/create-thumbnails.js#L4
https://github.com/htmlacademy-javascript/1932495-kekstagram-26/blob/8e9d2332cb07b954fb0ef13e1d64a9850e8cbe33/js/create-thumbnails.js#L7
https://github.com/htmlacademy-javascript/1932495-kekstagram-26/blob/8e9d2332cb07b954fb0ef13e1d64a9850e8cbe33/js/create-thumbnails.js#L9
</details>

```js
templatePicture instanceof Element; // true
// ...
```
Все эти переменные также указывают на DOM-элементы (= объекты типа `Element`), но в их названии не используется суффикс `Element`, что нарушает критерий по _единообразию_ в именовании.

Если для названий переменных с DOM-элементами **решила** использовать суффикс `Element`, то его следует использовать для всех подобных переменных _во всем проекте_ (и внимательно следить за этим). Или не использовать, то тогда суффикс `Element` нужно убрать.

[`Д 6`](https://up.htmlacademy.ru/javascript/26/criteries#d6)
> Используется единый стиль именования переменных

> если переменные, которые хранят [DOM-элемент](https://developer.mozilla.org/ru/docs/Web/API/Element), содержат слово `Element` или любое другое, **но одно и то же везде**

**JS2**-Д6
> если есть переменные, которые хранят [DOM-элемент](https://developer.mozilla.org/ru/docs/Web/API/Element) и содержат слово `Element`, **то это правило работает везде**

2022-06-27 18:34 UTC, AlexMasterov commented on js/create-photos.js
> +const somePhotos = () => Array.from({length: SIMILAR_PHOTO_COUNT}, createPhotos);
const `SIMILAR_PHOTO_COUNT` = 25;
const somePhotos = () => Array.from({length: `SIMILAR_PHOTO_COUNT`}, createPhotos);

В этой константе мало пользы и её расположение в модуле нарушает критерий.
 
[`Б 10`](https://up.htmlacademy.ru/javascript/26/criteries#b10)
> Список констант идёт перед основным кодом

```diff
- const somePhotos = () => Array.from({length: SIMILAR_PHOTO_COUNT}, createPhotos);
+ const somePhotos = () => Array.from({length: 25}, createPhotos);
```
Еще лучше: (см. снова https://github.com/htmlacademy-javascript/1932495-kekstagram-26/pull/3#discussion_r900399441)


```diff
- const somePhotos = () => Array.from({length: SIMILAR_PHOTO_COUNT}, createPhotos);
+ const somePhotos = (count) => Array.from({length: count}, createPhotos);
```

2022-06-27 18:34 UTC, AlexMasterov commented on js/create-photos.js
> +const somePhotos = () => Array.from({length: SIMILAR_PHOTO_COUNT}, createPhotos);
const `some`Photos = () => Array.from({length: SIMILAR_PHOTO_COUNT}, createPhotos);

[`Б 6`](https://up.htmlacademy.ru/javascript/26/criteries#b6)
> Название функции или метода содержит глагол [_в начале_]

2022-06-27 18:34 UTC, AlexMasterov commented on js/create-thumbnails.js
> +const TEST = somePhotos();
const `TEST` = somePhotos();

Это _по определению_ не может считаться "константой".

> Подобное не будет работать в языке с поддержкой _настоящих_ констант

[`Б 3`](https://up.htmlacademy.ru/javascript/26/criteries#b3)
> Названия переменных, параметров, свойств и методов начинаются со строчной буквы и записываются в нотации `camelCase`

```js
Array.isArray(TEST); // true
```
[`Б 5`](https://up.htmlacademy.ru/javascript/26/criteries#b5)
> Массивы названы существительными во множественном числе

2022-06-27 18:34 UTC, AlexMasterov commented on js/create-thumbnails.js
> +const TEST = somePhotos();
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/176007724-bf48f31c-4844-40ef-951e-ae2388956d94.png)

</details>

Функция `somePhotos` вместо создания одного массива с объектами данных фото создает и возвращает массив с массивами.

<details>
<summary>create-photos.js</summary>

https://github.com/htmlacademy-javascript/1932495-kekstagram-26/blob/8e9d2332cb07b954fb0ef13e1d64a9850e8cbe33/js/create-photos.js#L14-L26
https://github.com/htmlacademy-javascript/1932495-kekstagram-26/blob/8e9d2332cb07b954fb0ef13e1d64a9850e8cbe33/js/create-photos.js#L29
</details>

Чтобы подобный код заработал потребуется из функции `createPhotos` вынести код создания _одного_ объекта с данными фото в отдельную функции, которая могла бы получать значения `id` из параметра. 

> Только создав функцию-фабрику для кустарного производства _одного_ объекта можно легко перейти к массовому производству множества объектов в массиве с помощью `Array.from`.

Пока достаточно этого:
```js
const somePhotos = createPhotos(); 
```
См. также https://github.com/htmlacademy-javascript/1932495-kekstagram-26/pull/3#discussion_r901158787.

2022-06-27 18:34 UTC, AlexMasterov commented on js/create-thumbnails.js
> +const TEST = somePhotos();
<details>
<summary>create-thumbnails.js</summary>

https://github.com/htmlacademy-javascript/1932495-kekstagram-26/blob/8e9d2332cb07b954fb0ef13e1d64a9850e8cbe33/js/create-thumbnails.js#L9
https://github.com/htmlacademy-javascript/1932495-kekstagram-26/blob/8e9d2332cb07b954fb0ef13e1d64a9850e8cbe33/js/create-thumbnails.js#L13-L21
</details>

> Сейчас этот код может выполняться _один_ раз, при загрузки модуля. Этого хватит чтобы формально сдать задание, а в след. всё переделывать

Следовало на основа этого кода создать функцию или даже функции, чтобы далее, в рамках требований ТЗ, его _переиспользовать_ с разным состоянием массива: отсортированным, отфильтрованным и т.п.

<details>
<summary>create-thumbnails.js</summary>

https://github.com/htmlacademy-javascript/1932495-kekstagram-26/blob/8e9d2332cb07b954fb0ef13e1d64a9850e8cbe33/js/create-thumbnails.js#L7
https://github.com/htmlacademy-javascript/1932495-kekstagram-26/blob/8e9d2332cb07b954fb0ef13e1d64a9850e8cbe33/js/create-thumbnails.js#L21
</details>

Добавлять элементы в `DOM` можно _отдельной_ функцией в _отдельном_ модуле, например, в `gallery.js` или временно в `main.js`.

<details>
<summary>create-thumbnails.js</summary>

https://github.com/htmlacademy-javascript/1932495-kekstagram-26/blob/8e9d2332cb07b954fb0ef13e1d64a9850e8cbe33/js/create-thumbnails.js#L11
</details>

Следовало создать данные _один_ раз в `main.js` и дальше импортировать туда необходимые функции для рендера, а не наоборот.

> Сейчас приложение не является _модульным_ и этот негативный трек усиливается

2022-06-27 18:34 UTC, AlexMasterov commented on js/create-thumbnails.js
> +const templatePicture = document.querySelector('#picture').content;
const templatePicture = document.querySelector('#picture').`content`;

Желательно _явно_ найти нужный элемент.

> \+ определиться с именованием DOM-элементом: `template`Picture, similarList`Fragment`, picture`Element`..

Пример:
```diff
- const templatePicture = document.querySelector('#picture').content;
+ const pictureTemplateElement = document.querySelector('#picture').content.querySelector('.picture');
```

> picture`Template`Element, pictureTemplate`Element`

2022-06-27 18:34 UTC, AlexMasterov commented on js/create-thumbnails.js
> +similarPicture.appendChild(similarListFragment);
similarPicture.`appendChild`(similarListFragment);

В случае добавления элементов с данным фото через метод [`.append`](https://developer.mozilla.org/ru/docs/Web/API/Element/append) создавать фрагмент не потребуется. Но для этого нужно сначала создать массив с элементами и знать, как его сразу _весь_ передать в этот метод. Иначе разницы не будет.

2022-06-27 18:35 UTC, AlexMasterov commented on js/create-thumbnails.js
> +  pictureElement.querySelector('.picture__comments').textContent = picture.comments.length; //не определяется длина, и даже если её отключить - миниатюры не отображаются корректно
> не определяется длина, и даже если её отключить - миниатюры не отображаются корректно

См. https://github.com/htmlacademy-javascript/1932495-kekstagram-26/pull/5#discussion_r907665377.

2022-06-27 20:54 UTC, prokhanova-k commented on js/create-thumbnails.js
> +const TEST = somePhotos();
Не увидела прошлый комментарий, извини.
Всё исправлю.

2022-06-27 21:39 UTC, AlexMasterov commented on js/create-thumbnails.js
> +const TEST = somePhotos();
> Не увидела прошлый комментарий, извини.

Этот комментарий "скрыт" и поэтому не обязывает к исправлению, но показывает пример полезной доработки 😃

2022-06-28 16:32 UTC, prokhanova-k commented on js/create-thumbnails.js
> +const TEST = somePhotos();
> 



> create-thumbnails.js
> https://github.com/htmlacademy-javascript/1932495-kekstagram-26/blob/8e9d2332cb07b954fb0ef13e1d64a9850e8cbe33/js/create-thumbnails.js#L9
> 
> 
> https://github.com/htmlacademy-javascript/1932495-kekstagram-26/blob/8e9d2332cb07b954fb0ef13e1d64a9850e8cbe33/js/create-thumbnails.js#L13-L21
> 
> > Сейчас этот код может выполняться _один_ раз, при загрузки модуля. Этого хватит чтобы формально сдать задание, а в след. всё переделывать
> 
> Следовало на основа этого кода создать функцию или даже функции, чтобы далее, в рамках требований ТЗ, его _переиспользовать_ с разным состоянием массива: отсортированным, отфильтрованным и т.п.
> 

Не понимаю этого комментария. Имеется ввиду, что работает для частного случае и только при запуске? Окей. Массив будет тот же, только измененный? Имею ввиду, что если допустим там не будет likes. Это надо учитывать? Или он всегда будет. Дай мне больше разъяснений, пожалуйста.

2022-06-28 17:13 UTC, prokhanova-k commented on js/create-thumbnails.js
> +similarPicture.appendChild(similarListFragment);
Этот комментарий тоже не до конца понимаю. Сделала по аналогии с демо.

2022-06-29 05:14 UTC, AlexMasterov commented on js/gallery.js
> +export {pictureTemplateElement, similarElement};
> Не нужно экспортировать DOM-элементы 😟

Лучше создавай и экспортируй _функции_, которые используют DOM-элементы:

```js
// renderPictures
const addPictures = (photos) => { ... }
const clearPictures = () => { ... }
```

2022-06-29 05:14 UTC, AlexMasterov commented on js/create-photos.js
> +export {somePhotos};
От модуля с названием `create-photos`.js ожидаешь экспорт функции для создания объектов с данными изображений, а не сами объекты 😃

2022-06-29 05:14 UTC, AlexMasterov commented on js/create-thumbnails.js
> +import {somePhotos} from './create-photos.js';
Повторю, что `import` данных в модули кроме `main.js`  - неудачное решение, которое потом будет стоить доп. времени на исправления и доработку.

2022-06-29 05:14 UTC, AlexMasterov commented on js/gallery.js
> +const similarElement = document.querySelector('.pictures');
const `similar`Element = document.querySelector('.`pictures`');

🤔

2022-06-29 05:14 UTC, AlexMasterov commented on js/gallery.js
> +const pictureTemplateElement = document.querySelector('#picture').content.querySelector('.picture');
Это следует перенести в модуль непосредственного использования: `create-thumbnails`.js.

2022-06-29 05:14 UTC, AlexMasterov commented on js/create-thumbnails.js
> +somePhotos.forEach((picture) => {
some`Photo`s.forEach((`picture`) => {

А тут `photo` превращается в `picture` 😃

2022-06-29 05:17 UTC, merged