Правда или действие (часть 1)
htmlacademy-javascript/1932495-kekstagram-26 pull request #7
Opened 2022-07-08 10:35 UTC by prokhanova-k

---
:mortar_board: [Правда или действие (часть 1)](https://up.htmlacademy.ru/javascript/26/user/1932495/tasks/15)

2022-07-08 23:12 UTC, AlexMasterov requested changes

2022-07-08 23:12 UTC, AlexMasterov commented on js/big-picture.js
> +const onBigPhotoCancelButtonElement = () => {
https://github.com/htmlacademy-javascript/1932495-kekstagram-26/blob/2d200fa96a6c9d921c141e5ef40192f0e81f63c0/js/big-picture.js#L39

[`Д 4`](https://up.htmlacademy.ru/javascript/26/criteries#d4)
> `on` + `(на каком элементе)` + **что случилось**

```diff
- const onBigPhotoCancelButtonElement = () => {
+ const onBigPhotoCancelButtonClick = () => {
```

2022-07-08 23:12 UTC, AlexMasterov commented on js/form.js
> +  document.addEventListener('keydown', onEscapeKeydownForm);
document.addEventListener(`'keydown'`, onEscapeKeydown`Form`);

[`Д 4`](https://up.htmlacademy.ru/javascript/26/criteries#d4)
> `on` + `(на каком элементе)` + **что случилось**

2022-07-08 23:12 UTC, AlexMasterov commented on js/form.js
> +hashtagsFieldElement.addEventListener('keydown', onEscapeKeydownFormFocus);
commentFieldElement.addEventListener(`'keydown'`, onEscapeKeydown`FormFocus`);
hashtagsFieldElement.addEventListener(`'keydown'`, onEscapeKeydown`FormFocus`);

[`Д 4`](https://up.htmlacademy.ru/javascript/26/criteries#d4)
> `on` + `(на каком элементе)` + **что случилось**

2022-07-08 23:12 UTC, AlexMasterov commented on js/validation.js
> +  COMMENT_LENGTH: `Длина комментария может быть не более ${COMMENT_MAX_LENGTH} символов`,
const `messageFormError` = {

[`Б 8`](https://up.htmlacademy.ru/javascript/26/criteries#b8)
> Название классов, конструкторов и _перечислений_ начинается с заглавной буквы

_Перечисления_ считаются константами.

[`Б 10`](https://up.htmlacademy.ru/javascript/26/criteries#b10)
> Список констант идёт перед основным кодом

2022-07-08 23:12 UTC, AlexMasterov commented on js/validation.js
> +  const reValidHashtag = /^#[A-Za-zА-Яа-яЁё0-9]{1,19}$/;
const `re`ValidHashtag = /^#[A-Za-zА-Яа-яЁё0-9]{1,19}$/;

[`Б 4`](https://up.htmlacademy.ru/javascript/26/criteries#b4)
> В качестве имён переменных и свойств используются английские существительные

> Сокращения в словах запрещены

Обращаю внимание, что объект `RegExp` с регулярным выражением создается заново при каждом вызове функции `validateHashtags`, что неэффективно.

2022-07-08 23:12 UTC, AlexMasterov commented on js/validation.js
> +
<details>
<summary>validation.js</summary>

https://github.com/htmlacademy-javascript/1932495-kekstagram-26/blob/2d200fa96a6c9d921c141e5ef40192f0e81f63c0/js/validation.js#L19
https://github.com/htmlacademy-javascript/1932495-kekstagram-26/blob/2d200fa96a6c9d921c141e5ef40192f0e81f63c0/js/validation.js#L25
https://github.com/htmlacademy-javascript/1932495-kekstagram-26/blob/2d200fa96a6c9d921c141e5ef40192f0e81f63c0/js/validation.js#L31
</details>

[`Д 14`](https://up.htmlacademy.ru/javascript/26/criteries#d14)
> Отсутствует дублирование кода: повторяющиеся части кода переписаны как функции

2022-07-08 23:12 UTC, AlexMasterov commented on js/main.js
<details>
<summary>form.js</summary>

https://github.com/htmlacademy-javascript/1932495-kekstagram-26/blob/2d200fa96a6c9d921c141e5ef40192f0e81f63c0/js/form.js#L50
</details>

<details>
<summary>main.js</summary>

https://github.com/htmlacademy-javascript/1932495-kekstagram-26/blob/2d200fa96a6c9d921c141e5ef40192f0e81f63c0/js/main.js#L5-L7
</details>

При должной организации модулей подобного быть не должно 😟

2022-07-08 23:12 UTC, AlexMasterov commented on index.html
> +                      maxlength="140"></textarea>
https://github.com/htmlacademy-javascript/1932495-kekstagram-26/blob/2d200fa96a6c9d921c141e5ef40192f0e81f63c0/js/validation.js#L42

> пыталась реализовать отдельно проверку длины, но не вышло, оставляю себе на доработку

https://github.com/htmlacademy-javascript/1932495-kekstagram-26/blob/2d200fa96a6c9d921c141e5ef40192f0e81f63c0/index.html#L132-L133

Если хочешь, чтобы работал валидатор (и имел смысл), то тогда не стоило здесь задавать ограничения 😃

2022-07-08 23:12 UTC, AlexMasterov commented on js/form.js
> +
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/178080499-e8a890f5-0670-4e83-a772-78a19c11f98f.png)

</details>

Если закрыть форму для загрузки фотографий нажатием на клавишу `Esc`, то на `document` для `keydown` остается обработчик.

[`Б 26`](https://up.htmlacademy.ru/javascript/26/criteries#b26)
> Обработчики событий добавляются и удаляются своевременно

2022-07-08 23:12 UTC, AlexMasterov commented on js/form.js
> +
Если закрыть форму для загрузки фотографий нажатием на клавишу `Esc`, то потом она не открывается.

Нужно разобраться и исправить.

2022-07-08 23:12 UTC, AlexMasterov commented on js/form.js
> +
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/178080749-aa830c66-7b2a-43d1-a5fe-19293a330689.png)

</details>

Если ввести хэштеги, а потом задать пустое поле, то сообщения о валидации не пропадают.

Нужно разобраться и исправить.

2022-07-10 09:40 UTC, prokhanova-k commented on js/main.js
Я осознаю это, но пока не понимаю, как исправить, так как у меня не целая функция, а разрозненные куски, которые я пока не понимаю, как правильно объединить.

2022-07-10 10:14 UTC, AlexMasterov commented on js/form.js
> +  document.addEventListener('keydown', onEscapeKeydownClick);
document.addEventListener(`'keydown'`, onEscapeKeydown`Click`);

Д4

```diff
- document.addEventListener('keydown', onEscapeKeydownClick);
+ document.addEventListener('keydown', onEscapeKeydown);
```

2022-07-10 10:14 UTC, AlexMasterov commented on js/form.js
> +const closeUploudFileElement = () => {
```diff
- const closeUploudFileElement = () => {
+ const closeUploudFile = () => {
```

2022-07-10 10:14 UTC, AlexMasterov commented on js/form.js
> +hashtagsFieldElement.addEventListener('keydown', onEscapeKeydownFormFocusClick);
commentFieldElement.addEventListener(`'keydown'`, onEscapeKeydown`FormFocusClick`);
hashtagsFieldElement.addEventListener(`'keydown'` onEscapeKeydown`FormFocusClick`);

Д4

Не исправлено.

2022-07-10 10:14 UTC, AlexMasterov commented on js/validation.js
> +const getHashtags = (string) => string.toLowerCase().trim().split(' ');
```diff
- const getHashtags = (string) => string.toLowerCase().trim().split(' ');
+ const parseHashtagsInput = (value) => value.toLowerCase().trim().split(' ');
```

2022-07-10 10:14 UTC, AlexMasterov commented on js/validation.js
> +const getHashtags = (string) => string.toLowerCase().trim().split(' ');
```js
''.string.toLowerCase().trim().split(' ') // ['']
```
Подобное поведение может привести к проблемам и усложнить логику валидации.

https://github.com/htmlacademy-javascript/1932495-kekstagram-26/blob/246b0c9e90dcf01152d3a0c704fd75d7fbcc8587/js/validation.js#L22

`|| value === ''`

Уже 😃

2022-07-10 10:14 UTC, merged

2022-07-15 11:45 UTC, prokhanova-k commented on js/validation.js
> +const getHashtags = (string) => string.toLowerCase().trim().split(' ');
Не понимаю это.

2022-07-15 16:06 UTC, AlexMasterov commented on js/validation.js
> +const getHashtags = (string) => string.toLowerCase().trim().split(' ');
> Не понимаю это

См. https://github.com/htmlacademy-javascript/1932495-kekstagram-26/pull/7#discussion_r917372686.

2022-07-15 16:07 UTC, AlexMasterov commented on js/validation.js
> +const RegExpHashtagValid = /^#[A-Za-zА-Яа-яЁё0-9]{1,19}$/;
const `R`egExpHashtagValid = /^#[A-Za-zА-Яа-яЁё0-9]{1,19}$/;

[`Б 3`](https://up.htmlacademy.ru/javascript/26/criteries#b3)
> Названия переменных, параметров, свойств и методов начинаются со строчной буквы и записываются в нотации `camelCase`